[tool.poetry]
name = "bee-copy"
version = "0.1.0"
description = ""
authors = ["bhudson <brian.hudson@flexential.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
